apiVersion: v1
kind: Service
metadata:
  name: sistema-noticias-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: sistema-noticias
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
